### ISSUE TITLE
Reset concentration after each time step

### ISSUE THREAD

**Issue by mzamyatina** [barronh/kpp#2]
Hi,
Is it possible to reset the concentrations of particular species to some custom concentrations on each time step? For example, if I want to keep the sum of NO and NO2 fixed during the simulation, but allow concentrations of NO and NO2 to vary with time. In other words, I tried to use the following code 
```fortran
SUBROUTINE update_nox(VAR, ind_NO, ind_NO2)
    USE MCM_Parameters, ONLY: NVAR
    REAL(8) :: NOX, NOXES
    REAL(8), INTENT(INOUT) :: VAR(NVAR)
    INTEGER, INTENT(IN) :: ind_NO, ind_NO2
    ! NOX is the value that (NO+NO2) is adjusted to on each time step
    NOX = 2.43e+07
    NOXES = VAR(ind_NO) + VAR(ind_NO2)
    VAR(ind_NO) = NOX * VAR(ind_NO) / NOXES
    VAR(ind_NO2) = NOX * VAR(ind_NO2) / NOXES
    ! PRINT *, NOXES
END SUBROUTINE update_nox
```
and its variation with C array instead of VAR, but I got strange results. Figure below shows the time series for NO, NO2 and NOx from two experiments. Each experiment is initialised with 1 ppt of NO, zero NO2, and some values for O3, CO, CH4, M, N2, O2, H2O. In 'ctrl' experiment I don't call update_nox() subroutine, in 'update_nox' I call it. It seems that NO and NO2 in 'update_nox' run are updated, but in some inconsistent way. However, when I print out NOXES within the subroutine, I get the correct value, 2.43e+07.
Is it something to do with how the integrator works? I am using LSODE.
Could you, please, help me?
![fig4](https://cloud.githubusercontent.com/assets/6954778/24430212/70bf869e-140d-11e7-9790-7c7c80e1778a.png)

**Comment by barronh** [comment]
Look at the DSMACC repository that has this feature already.

**Comment by mzamyatina** [comment]
Thank you! I'll have a look.
