### ISSUE TITLE
KPP for full MCM mechanism translation

### ISSUE THREAD

**Issue by xk-y** [barronh/kpp#6]
Hi Barron,

  This is really a great modification of KPP : ) 
  I am trying to use the modified KPP to translate the full MCM v3.2 mechanism (approximately 5035 species, 16404 reactions) into Fortran 90 code, and it seems to be a long journey. How much time would you expect it to take on PC? 

Best,
xiaokai

**Comment by barronh** [comment]
Good question, but I don’t do it on a PC nor do I have timing results.
